version: '3.4'
services:
  jira:
    image: cptactionhank/atlassian-jira:latest
    restart: always
    container_name: jira
    links:
      - database
    volumes:
      - jira-data:/var/atlassian/jira

  confluence:
    image: cptactionhank/atlassian-confluence:latest
    restart: always
    container_name: confluence
    links:
      - database
    volumes:
      - confluence-data:/var/atlassian/confluence

  database:
    image: postgres:latest
    restart: always
    hostname: postgresql
    container_name: postgresql
    volumes:
      - database-data:/var/lib/postgresql/data
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    links:
      - jira
      - confluence
    volumes:
    - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
    - DOMAIN
volumes:
  jira-data:
  confluence-data:
  database-data:
